name: Docker Image CI

run-name: '${{ github.actor }} [DOCKER]: Run tests'

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Bring up services
      run: docker compose up -d

    - name: Wait for services
      run: sleep 5

    - name: curl to Client
      run: curl -s http://localhost:5000/

    - name: curl to Server
      run: curl -s http://localhost:3000/
